Repository apache/incubator-kie-kogito-apps, pull requests merged in 2022-01, with the labels that each got.

#1091 FAI-663: Add initial support for remaining input features in CF as constrained
  explainability/explainability-core/src/main/java/org/kie/kogito/explainability/local/counterfactual/entities/CounterfactualEntityFactory.java
  explainability/explainability-core/src/main/java/org/kie/kogito/explainability/local/counterfactual/entities/fixed/FixedBinaryEntity.java
  explainability/explainability-core/src/main/java/org/kie/kogito/explainability/local/counterfactual/entities/fixed/FixedCompositeEntity.java
  explainability/explainability-core/src/main/java/org/kie/kogito/explainability/local/counterfactual/entities/fixed/FixedCurrencyEntity.java
  explainability/explainability-core/src/main/java/org/kie/kogito/explainability/local/counterfactual/entities/fixed/FixedDurationEntity.java
  explainability/explainability-core/src/main/java/org/kie/kogito/explainability/local/counterfactual/entities/fixed/FixedTextEntity.java
  explainability/explainability-core/src/main/java/org/kie/kogito/explainability/local/counterfactual/entities/fixed/FixedTimeEntity.java
  explainability/explainability-core/src/main/java/org/kie/kogito/explainability/local/counterfactual/entities/fixed/FixedURIEntity.java
  explainability/explainability-core/src/main/java/org/kie/kogito/explainability/local/counterfactual/entities/fixed/FixedVectorEntity.java
  explainability/explainability-core/src/test/java/org/kie/kogito/explainability/local/counterfactual/CounterfactualEntityFactoryTest.java
  explainability/explainability-core/src/test/java/org/kie/kogito/explainability/local/counterfactual/entities/SimilarityTest.java
Labels: enhancement

#1208 FAI-701: Fix edge case in CF primary soft score calculation
  explainability/explainability-core/src/main/java/org/kie/kogito/explainability/local/counterfactual/CounterFactualScoreCalculator.java
  explainability/explainability-core/src/test/java/org/kie/kogito/explainability/local/counterfactual/CounterfactualScoreCalculatorTest.java
Labels: bug

#1213 [1.16.x] Bump Quarkus version to 2.7.0.Final
  task-assigning/task-assigning-service/src/test/java/org/kie/kogito/taskassigning/service/messaging/ReactiveMessagingEventConsumerTest.java
Labels: dsl-test
